version: '3.3'
services:
  app:
    image: nest-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
