FROM node:alpine

RUN apk add

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm ci

# Copy app source
COPY . .

RUN npm i -g @nestjs/cli
# Build app
RUN npm run build

# Expose port and start the app
EXPOSE 3001
CMD [ "npm","run","start" ]
