FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN yarn ci

# Copy app source
COPY . .

# Build app
RUN yarn build

# Expose port and start the app
EXPOSE 3001
CMD [ "yarn","start:prod" ]
