version: "3.3"
services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: frontend
    # ports:
    #   - "3000:3000"
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: backend
    # ports:
    #   - "3001:3001"