FROM node:14-alpine

# Create and set the working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the source code
COPY . .

# Expose the application port
EXPOSE 3001

# Start the development server
CMD [ "npm", "run", "start:dev" ]